/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH
 * under one or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information regarding copyright
 * ownership. Camunda licenses this file to you under the Apache License,
 * Version 2.0; you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.finos.fluxnova.bpm.engine.test.api.authorization;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Fail.fail;
import static org.finos.fluxnova.bpm.engine.authorization.Authorization.ANY;
import static org.finos.fluxnova.bpm.engine.authorization.Permissions.TASK_ASSIGN;
import static org.finos.fluxnova.bpm.engine.authorization.Permissions.UPDATE;
import static org.finos.fluxnova.bpm.engine.authorization.Permissions.UPDATE_TASK;
import static org.finos.fluxnova.bpm.engine.authorization.Resources.PROCESS_DEFINITION;
import static org.finos.fluxnova.bpm.engine.authorization.Resources.TASK;

import java.util.Arrays;
import java.util.Date;
import java.util.List;
import org.finos.fluxnova.bpm.engine.AuthorizationException;
import org.finos.fluxnova.bpm.engine.TaskService;
import org.finos.fluxnova.bpm.engine.task.Task;
import org.finos.fluxnova.bpm.engine.test.util.ClockTestUtil;
import org.finos.fluxnova.bpm.engine.test.util.EntityRemoveRule;
import org.finos.fluxnova.bpm.engine.test.util.ObjectProperty;
import org.finos.fluxnova.bpm.engine.test.util.RemoveAfter;
import org.finos.fluxnova.bpm.engine.test.util.TriConsumer;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

public class SetTaskPropertyAuthorizationTest extends AuthorizationTest {

  protected static final String PROCESS_KEY = "oneTaskProcess";

  @RegisterExtension
  public EntityRemoveRule entityRemoveRule = EntityRemoveRule.of(testRule);
  public String operationName;
  public TriConsumer<TaskService, String, Object> operation;
  public String taskId;
  public Object value;

  protected boolean deleteTask;

  /**
   * Parameters:
   * <p>
   * simpleMethodName: Used for readability (printing first argument as test method instead of a autogenerated consumer name)
   * methodToCall: The method to call during test cases
   * setValue: The value to use to set property to
   * taskQueryBuilderMethodName: The corresponding taskQuery builder method name to use for assertion purposes
   */
  public static List<Object[]> data() {
    TriConsumer<TaskService, String, Object> setPriority = (taskService, taskId, value) -> taskService.setPriority(taskId, (int) value);
    TriConsumer<TaskService, String, Object> setName = (taskService, taskId, value) -> taskService.setName(taskId, (String) value);
    TriConsumer<TaskService, String, Object> setDescription = (taskService, taskId, value) -> taskService.setDescription(taskId, (String) value);
    TriConsumer<TaskService, String, Object> setDueDate = (taskService, taskId, value) -> taskService.setDueDate(taskId, (Date) value);
    TriConsumer<TaskService, String, Object> setFollowUpDate = (taskService, taskId, value) -> taskService.setFollowUpDate(taskId, (Date) value);

    return Arrays.asList(new Object[][] {
        {"setPriority", setPriority, "taskId", 80 },
        {"setName", setName, "taskId", "name" },
        {"setDescription", setDescription, "taskId", "description" },
        {"setDueDate", setDueDate, "taskId",  ClockTestUtil.setClockToDateWithoutMilliseconds() },
        {"setFollowUpDate", setFollowUpDate, "taskId", ClockTestUtil.setClockToDateWithoutMilliseconds() }
    });
  }

  @Override
  @BeforeEach
  public void setUp() throws Exception {
    testRule.deploy("org/finos/fluxnova/bpm/engine/test/api/oneTaskProcess.bpmn20.xml");
    super.setUp();
  }

  @MethodSource("data")
  @ParameterizedTest(name = "{0}")
  @RemoveAfter
  public void shouldSetOperationStandaloneWithoutAuthorization(String operationName, TriConsumer<TaskService, String, Object> operation, String taskId, Object value) {
    initSetTaskPropertyAuthorizationTest(operationName, operation, taskId, value);
    // given
    createTask(taskId);

    try {
      // when
      operation.accept(taskService, taskId, value);
      fail("Exception expected: It should not be possible to " + operationName);
    } catch (AuthorizationException e) {
      // then
      testRule.assertTextPresent(
          "The user with id '" + userId + "' does not have one of the following permissions: 'TASK_ASSIGN'",
          e.getMessage());
    }
  }

  @MethodSource("data")
  @ParameterizedTest(name = "{0}")
  @RemoveAfter
  public void shouldSetOperationStandalone(String operationName, TriConsumer<TaskService, String, Object> operation, String taskId, Object value) {
    initSetTaskPropertyAuthorizationTest(operationName, operation, taskId, value);
    // given
    createTask(taskId);
    createGrantAuthorization(TASK, taskId, userId, UPDATE);

    // when
    operation.accept(taskService, taskId, value);

    // then
    Task task = selectSingleTask();

    assertThat(task).isNotNull();
    assertHasPropertyValue(task, operationName, value);
  }

  @MethodSource("data")
  @ParameterizedTest(name = "{0}")
  @RemoveAfter
  public void shouldSetOperationStandaloneWithTaskAssignPermission(String operationName, TriConsumer<TaskService, String, Object> operation, String taskId, Object value) {
    initSetTaskPropertyAuthorizationTest(operationName, operation, taskId, value);
    // given
    createTask(taskId);
    createGrantAuthorization(TASK, taskId, userId, TASK_ASSIGN);

    // when
    operation.accept(taskService, taskId, value);

    // then
    Task task = selectSingleTask();

    assertThat(task).isNotNull();
    assertHasPropertyValue(task, operationName, value);
  }

  @MethodSource("data")
  @ParameterizedTest(name = "{0}")
  public void shouldSetOperationOnProcessWithTaskAssignPermissionOnTask(String operationName, TriConsumer<TaskService, String, Object> operation, String taskId, Object value) {
    initSetTaskPropertyAuthorizationTest(operationName, operation, taskId, value);
    // given
    startProcessInstanceByKey(PROCESS_KEY);
    String processTaskId = selectSingleTask().getId();

    createGrantAuthorization(TASK, processTaskId, userId, TASK_ASSIGN);

    // when
    operation.accept(taskService, processTaskId, value);

    // then
    Task task = selectSingleTask();

    assertThat(task).isNotNull();
    assertHasPropertyValue(task, operationName, value);
  }

  @MethodSource("data")
  @ParameterizedTest(name = "{0}")
  public void shouldSetOperationOnProcessWithoutAuthorization(String operationName, TriConsumer<TaskService, String, Object> operation, String taskId, Object value) {
    initSetTaskPropertyAuthorizationTest(operationName, operation, taskId, value);
    // given
    startProcessInstanceByKey(PROCESS_KEY);
    String processTaskId = selectSingleTask().getId();

    try {
      // when
      operation.accept(taskService, processTaskId, value);
      fail("Exception expected: It should not be possible to " + operationName);
    } catch (AuthorizationException e) {
      // then
      String message = e.getMessage();
      testRule.assertTextPresent(userId, message);
      testRule.assertTextPresent(UPDATE.getName(), message);
      testRule.assertTextPresent(processTaskId, message);
      testRule.assertTextPresent(TASK.resourceName(), message);
      testRule.assertTextPresent(UPDATE_TASK.getName(), message);
      testRule.assertTextPresent(PROCESS_DEFINITION.resourceName(), message);
    }
  }

  @MethodSource("data")
  @ParameterizedTest(name = "{0}")
  public void shouldSetOperationOnProcessWithUpdatePermissionOnAnyTask(String operationName, TriConsumer<TaskService, String, Object> operation, String taskId, Object value) {
    initSetTaskPropertyAuthorizationTest(operationName, operation, taskId, value);
    // given
    startProcessInstanceByKey(PROCESS_KEY);
    String processTaskId = selectSingleTask().getId();

    createGrantAuthorization(TASK, ANY, userId, UPDATE);

    // when
    operation.accept(taskService, processTaskId, value);

    // then
    Task task = selectSingleTask();

    assertThat(task).isNotNull();
    assertHasPropertyValue(task, operationName, value);
  }

  @MethodSource("data")
  @ParameterizedTest(name = "{0}")
  public void shouldSetOperationOnProcessWithTaskAssignPermissionOnAnyTask(String operationName, TriConsumer<TaskService, String, Object> operation, String taskId, Object value) {
    initSetTaskPropertyAuthorizationTest(operationName, operation, taskId, value);
    // given
    startProcessInstanceByKey(PROCESS_KEY);
    String processTaskId = selectSingleTask().getId();

    createGrantAuthorization(TASK, ANY, userId, TASK_ASSIGN);

    // when
    operation.accept(taskService, processTaskId, value);

    // then
    Task task = selectSingleTask();

    assertThat(task).isNotNull();
    assertHasPropertyValue(task, operationName, value);
  }

  @MethodSource("data")
  @ParameterizedTest(name = "{0}")
  public void shouldSetOperationOnProcessWithUpdateTasksPermissionOnProcessDefinition(String operationName, TriConsumer<TaskService, String, Object> operation, String taskId, Object value) {
    initSetTaskPropertyAuthorizationTest(operationName, operation, taskId, value);
    // given
    startProcessInstanceByKey(PROCESS_KEY);
    String processTaskId = selectSingleTask().getId();

    createGrantAuthorization(PROCESS_DEFINITION, PROCESS_KEY, userId, UPDATE_TASK);

    // when
    operation.accept(taskService, processTaskId, value);

    // then
    Task task = selectSingleTask();

    assertThat(task).isNotNull();
    assertHasPropertyValue(task, operationName, value);
  }

  @MethodSource("data")
  @ParameterizedTest(name = "{0}")
  public void shouldSetOperationOnProcessWithTaskAssignPermissionOnProcessDefinition(String operationName, TriConsumer<TaskService, String, Object> operation, String taskId, Object value) {
    initSetTaskPropertyAuthorizationTest(operationName, operation, taskId, value);
    // given
    startProcessInstanceByKey(PROCESS_KEY);
    String processTaskId = selectSingleTask().getId();

    createGrantAuthorization(PROCESS_DEFINITION, PROCESS_KEY, userId, TASK_ASSIGN);

    // when
    operation.accept(taskService, processTaskId, value);

    // then
    Task task = selectSingleTask();

    assertThat(task).isNotNull();
    assertHasPropertyValue(task, operationName, value);
  }

  @MethodSource("data")
  @ParameterizedTest(name = "{0}")
  public void shouldSetOperationOnProcessTask(String operationName, TriConsumer<TaskService, String, Object> operation, String taskId, Object value) {
    initSetTaskPropertyAuthorizationTest(operationName, operation, taskId, value);
    // given
    startProcessInstanceByKey(PROCESS_KEY);
    String processTaskId = selectSingleTask().getId();

    createGrantAuthorization(TASK, processTaskId, userId, UPDATE);
    createGrantAuthorization(PROCESS_DEFINITION, PROCESS_KEY, userId, UPDATE_TASK);

    // when
    operation.accept(taskService, processTaskId, value);

    // then
    Task task = selectSingleTask();

    assertThat(task).isNotNull();
    assertHasPropertyValue(task, operationName, value);
  }

  @MethodSource("data")
  @ParameterizedTest(name = "{0}")
  public void shouldSetOperationOnProcessWithTaskAssignPermission(String operationName, TriConsumer<TaskService, String, Object> operation, String taskId, Object value) {
    initSetTaskPropertyAuthorizationTest(operationName, operation, taskId, value);
    // given
    startProcessInstanceByKey(PROCESS_KEY);
    String processTaskId = selectSingleTask().getId();

    createGrantAuthorization(TASK, processTaskId, userId, TASK_ASSIGN);
    createGrantAuthorization(PROCESS_DEFINITION, PROCESS_KEY, userId, TASK_ASSIGN);

    // when
    operation.accept(taskService, processTaskId, value);

    // then
    Task task = selectSingleTask();

    assertThat(task).isNotNull();
    assertHasPropertyValue(task, operationName, value);
  }

  private void assertHasPropertyValue(Task task, String operationName, Object expectedValue) {
    try {
      Object value = ObjectProperty.ofSetterMethod(task, operationName).getValue();

      assertThat(value).isEqualTo(expectedValue);
    } catch (Exception e) {
      fail("Failed to assert property for operationName=" + operationName + " due to : " + e.getMessage());
    }
  }

  public void initSetTaskPropertyAuthorizationTest(String operationName, TriConsumer<TaskService, String, Object> operation, String taskId, Object value) {
    this.operationName = operationName;
    this.operation = operation;
    this.taskId = taskId;
    this.value = value;
  }
}